# Generated by Django 2.2.5 on 2019-10-10 12:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250)),
                ('mal_id', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('english', models.CharField(blank=True, max_length=1000, null=True)),
                ('japanese', models.CharField(blank=True, max_length=1000, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('aired', models.CharField(blank=True, max_length=50, null=True)),
                ('premiered', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('english_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('default_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('aired', models.CharField(blank=True, max_length=50, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Anime')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_ep', to='api.Episode')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_ep', to='api.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('subbed', 'Subbed'), ('dubbed', 'Dubbed')], max_length=10)),
                ('quality', models.CharField(blank=True, max_length=20, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
