# Generated by Django 2.2.5 on 2019-09-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('english', models.CharField(blank=True, max_length=200, null=True)),
                ('japanese', models.CharField(blank=True, max_length=200, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('dated', models.DateTimeField()),
                ('aired', models.CharField(blank=True, max_length=50, null=True)),
                ('premiered', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('english_name', models.CharField(blank=True, max_length=200, null=True)),
                ('default_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('image', models.URLField(blank=True, null=True)),
                ('aired', models.CharField(blank=True, max_length=50, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Anime')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_ep', to='api.Episode')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_ep', to='api.Episode')),
            ],
        ),
    ]
