# Generated by Django 2.2.5 on 2019-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='dated',
            new_name='date',
        ),
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
