# Generated by Django 2.2.5 on 2019-09-13 18:33

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190913_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='links',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
