# Generated by Django 2.2.5 on 2019-09-13 21:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_episode_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
