# Generated by Django 2.2.5 on 2019-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190913_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='default_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='english_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
