# Generated by Django 2.2.5 on 2019-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190914_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
