# Generated by Django 2.2.5 on 2019-09-14 08:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190914_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
