# Generated by Django 2.2.5 on 2019-09-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190914_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
