# Generated by Django 2.2.5 on 2019-09-14 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190914_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=datetime.datetime(2019, 9, 14, 11, 45, 41, 448766), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=datetime.datetime(2019, 9, 14, 11, 45, 49, 593950), max_length=250),
            preserve_default=False,
        ),
    ]
