# Generated by Django 2.2.5 on 2019-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
