# Generated by Django 2.2.5 on 2019-09-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190922_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
