# Generated by Django 2.2.5 on 2019-09-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190923_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='links',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('subbed', 'Subbed'), ('dubbed', 'Dubbed')], max_length=10)),
                ('quality', models.CharField(blank=True, max_length=20, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Episode')),
            ],
        ),
    ]
